language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"
install:
- python setup.py develop
- pip install nose mock
script: nosetests -x tests/*.py
notifications:
    email: true
    irc:
        - "irc.freenode.net#threebean"
    on_success: change
    on_failure: always
